version: '3.7'

services:
  aws:
    image: localstack/localstack
    ports:
      - 4568:4566
    volumes:
      - ./scripts/localstack:/docker-entrypoint-initaws.d
    environment:
      - SERVICES=events,sqs
      - DEFAULT_REGION=us-west-1